/**
 * Created with JetBrains WebStorm.
 * User: ty
 * Date: 14-10-5
 * Time: 下午5:34
 * To change this template use File | Settings | File Templates.
 */
var config={
    qiNiu:{
        uploadDomain:"http://qiniu-plupload.qiniudn.com/",
        bucketDomain:"http://7vilpp.com1.z0.glb.clouddn.com/"
    },
    ajaxUrls:{
        upload:"http://121.40.16.252/asset_hub/qiniu/uptoken"
    },
    upload:{
        sizes:{
            all:"5120m"
        },
        filters:{
            all:"*",
            zip:"zip,ZIP",
            img:"jpg,JPG,jpeg,JPEG,png,PNG"
        }
    },
    validError:{
        required:"请输入此字段！",
        email:"请输入正确的邮箱格式！",
        emailExist:"邮箱已经存在！",
        uploadImg:"请上传图片！",
        number:"请输入数字",
        maxLength:"此字段最多输入${max}个字！",
        minLength:"此字段最少输入${min}个字！",
        rangLength:"此字段只能输入${min}-${max}个字！",
        pwdNotEqual:"两次输入的密码不一样！"
    },
    message:{
        optSuccess:"操作成功！",
        noData:"没有数据",
        progress:"处理中...",
        uploaded:"上传完成！",
        confirmDelete:"确定删除吗？",
        noSelected:"没有选中任何记录！",
        notFound:"资源丢失！",
        loadDataError:"请求数据失败！",
        studentNotFound:"学号不存在，请核对后再提交！",
        networkError:"网络异常，请稍后重试！",
        systemError:"系统错误，请稍后重试或者联系mail@lotusprize.com！",
        optSuccRedirect:"操作成功,3秒后跳转到管理页！",
        timeout:"登录超时，3秒后自动跳到登陆页！",
        imageNot300x300:"图片不是300x300像素！",
        imageMoreThan4:"最多上传4张图片！",
        imageNot600x400:"${filename}不是600x400像素！",
        optError:"服务器端异常，请稍后重试！",
        uploadSizeError:"最大文件大小${value}！",
        uploadExtensionError:"只允许上传${value}！",
        fileNameTooLong:"文件名过长，最大长度为${value}个字！",
        stepOneUnComplete:"第一步有未填写字段！",
        stepTwoUnComplete:"没有上传文件或者有文件正在上传！"
    },
    data:{
        1:{
            thumb:"../../data/images/work/1/01.jpg",
            title:"这湘有礼",
            score:0
        },
        2:{
            thumb:"../../data/images/work/2/02.jpg",
            title:"农耕包袋设计",
            score:0
        },
        3:{
            thumb:"../../data/images/work/3/03.png",
            title:"四季稻",
            score:4.35
        },
        4:{
            thumb:"../../data/images/work/4/04.jpg",
            title:"军人本色-单肩包系列",
            score:4.22
        },
        5:{
            thumb:"../../data/images/work/5/05.png",
            title:"湘楚漆器文化桌面文具产品",
            score:3.64
        },
        6:{
            thumb:"../../data/images/work/6/06.jpg",
            title:"鹿角便携式餐具套装",
            score:4.05
        },
        7:{
            thumb:"../../data/images/work/7/07.jpg",
            title:"岳麓书院剪纸-明信片版",
            score:4.38
        },
        8:{
            thumb:"../../data/images/work/8/08.jpg",
            title:"岳麓八景系列产品",
            score:4.40
        },
        9:{
            thumb:"../../data/images/work/9/09.jpg",
            title:"岳麓书院时间印记",
            score:4.28
        },
        10:{
            thumb:"../../data/images/work/10/010.jpg",
            title:"岳麓书院铭文系列-杯垫",
            score:4.26
        },
        11:{
            thumb:"../../data/images/work/11/011.jpg",
            title:"书院文化产品-回形针",
            score:3.59
        },
        12:{
            thumb:"../../data/images/work/12/012.jpg",
            title:"蓝.隐山 侗族手工织锦亚麻围巾",
            score:4.49
        },
        13:{
            thumb:"../../data/images/work/13/013.jpg",
            title:"花瑶图案设计及应用",
            score:4.19
        },
        14:{
            thumb:"../../data/images/work/14/014.jpg",
            title:"花瑶挑花布鞋",
            score:3.99
        },
        15:{
            thumb:"../../data/images/work/15/015.jpg",
            title:"金银花茶叶包装",
            score:3.64
        },
        16:{
            thumb:"../../data/images/work/16/016.jpg",
            title:"DIY手工织带套装",
            score:3.98
        },
        17:{
            thumb:"../../data/images/work/17/017.png",
            title:"竹文化室内照明灯具",
            score:3.78
        },
        18:{
            thumb:"../../data/images/work/18/018.png",
            title:"光阴圆舞曲",
            score:4.10
        },
        19:{
            thumb:"../../data/images/work/19/019.jpg",
            title:"花与瓷",
            score:4.28
        },
        20:{
            thumb:"../../data/images/work/20/020.jpg",
            title:"“桐”（铜+木）实木家具",
            score:4.18
        },
        21:{
            thumb:"../../data/images/work/21/021.jpg",
            title:"双色迷彩伟人肖像系列",
            score:3.06
        },
        22:{
            thumb:"../../data/images/work/22/022.jpg",
            title:"岳麓书院铭文系列-杯垫",
            score:3.28
        },
        23:{
            thumb:"../../data/images/work/23/023.jpg",
            title:"基于湖湘漆器文化的桌面文具产品设计",
            score:3.20
        },
        24:{
            thumb:"../../data/images/work/24/024.jpg",
            title:"花瑶挑花相机带基本款",
            score:3.84
        },
        25:{
            thumb:"../../data/images/work/25/025.jpg",
            title:"花瑶挑花DIY手工织带套装",
            score:3.95
        },
        26:{
            thumb:"../../data/images/work/26/026.jpg",
            title:"书院九号总理套餐",
            score:3.77
        },
        27:{
            thumb:"../../data/images/work/27/027.jpg",
            title:"鸟衣架",
            score:3.57
        },
        28:{
            thumb:"../../data/images/work/28/028.jpg",
            title:"岳麓书院“窗花”系列",
            score:3.02
        },
        29:{
            thumb:"../../data/images/work/29/029.jpg",
            title:"垂花柱精油瓶子",
            score:3.24
        },
        30:{
            thumb:"../../data/images/work/30/030.jpg",
            title:"电子产品收纳包",
            score:3.23
        },
        31:{
            thumb:"../../data/images/work/31/031.jpg",
            title:"岳麓书院厨具系列",
            score:2.90
        },
        32:{
            thumb:"../../data/images/work/32/032.jpg",
            title:"踏歌堂纹果盘设计",
            score:3.81
        },
        33:{
            thumb:"../../data/images/work/33/033.jpg",
            title:"木踏歌行 侗族手工织锦亚麻围巾",
            score:4.10
        }
    }
};